### ISSUE TITLE
level=error msg="Error during scrape: too many requests"

### ISSUE THREAD

**Issue by urbaman** [xperimental/nextcloud-exporter#106]
Hi,

Deployed in kubernetes, can't seem to be able to scrape, while the serverinfo page responds via blowser.
It seems the exporter keeps running every 5s (default timeout) even if I try to set it to 30s, and it's too frequent.

Running Nextcloud 28.0.1.1

Logs:

```
kubectl logs -n nextcloud nextcloud-exporter-85d86498c9-q8prb
level=info msg="nextcloud-exporter 0.6.2"
level=info msg="Nextcloud server: https://nextcloud.urbaman.it User: admin"
level=info msg="Listen on :9205..."
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
level=error msg="Error during scrape: too many requests"
```

Deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-exporter
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-exporter
  template:
    metadata:
      labels:
        app: nextcloud-exporter
    spec:
      containers:
      - name: nextcloud-exporter
        image: xperimental/nextcloud-exporter:latest
        ports:
        - containerPort: 9205
          name: metrics
        env:
          #        - name: NEXTCLOUD_AUTH_TOKEN
          #          value: "JJrbN-iD8pi-aDYMp-geias-3Jmqk"
        - name: NEXTCLOUD_USERNAME
          value: "admin"
        - name: NEXTCLOUD_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ADMIN_PASSWORD
              name: nextcloud-secrets
        - name: NEXTCLOUD_SERVER
          value: "https://nextcloud.domain.com"
        - name: NEXTCLOUD_TIMEOUT
          value: "30s"
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-exporter
  namespace: nextcloud
  labels:
    app: nextcloud-exporter
spec:
  type: ClusterIP
  ports:
  - port: 9205
    protocol: TCP
    name: http
  selector:
    app: nextcloud-exporte
```
