### ISSUE TITLE
Changing content of metrics

### ISSUE THREAD

**Issue by plazotronik** [xperimental/nextcloud-exporter#124]
How can I disabled **GC_COLLECTOR** (go_\*) and **PROCESS_COLLECTOR** (process_*) in metrics?

**Comment by xperimental** [comment]
I think I would solve this with a `metric_relabel_config` in Prometheus (this example just keeps all the `nextcloud_*` metrics:

```yaml
scrape_configs:
- job_name: nextcloud
  # [...]
  metric_relabel_configs:
  - source_labels: ["__name__"]
    regex: "nextcloud_.+"
    action: keep
```
