### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by chapa** [xperimental/nextcloud-exporter#14]
Hi,

I don't understand why, but I can't make this exporter working.
Here is the docker-compose.yaml file I use to setup a nextcloud and this exporter :
```yaml
version: '2'

services:
  app:
    image: nextcloud:18.0.3-apache
    volumes:
      - ./volumes/nextcloud:/var/www/html
    ports:
      - "8000:80"

  prometheus-exporter:
    image: xperimental/nextcloud-exporter:v0.1.0
    environment:
      - NEXTCLOUD_SERVERINFO_URL=http://app
      - NEXTCLOUD_USERNAME=nextcloud
      - NEXTCLOUD_PASSWORD=nextcloud
    ports:
      - "9205:9205"
```

Just after the first `docker-compose up -d`, go to http://localhost:8000 and create a user `nextcloud` with the password `nextcloud`.
See that http://localhost:8000/ocs/v2.php/apps/serverinfo/api/v1/info is working correctly.
But http://localhost:9205/metrics doesn't write nextcloud values because it can't get data from nextcloud.

Here is the result of `docker-compose logs` :
```
app_1                  | 172.20.0.2 - nextcloud [29/Apr/2020:09:15:53 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info HTTP/1.1" 400 5488 "-" "Go-http-client/1.1"
prometheus-exporter_1  | 2020/04/29 09:15:53 Error during scrape: unexpected status code: 400
```

Is there something I'm missing ?
