### ISSUE TITLE
Error on parsing monitoring-url with port-value

### ISSUE THREAD

**Issue by afischer211** [xperimental/nextcloud-exporter#8]
If the nextcloud-instance runs on a non-standard port, you must give the port-number to the monitoring-url. But the exporter fails on start with error about the url.

**Comment by xperimental** [comment]
Thanks for the report. I'll look into it.

**Comment by xperimental** [comment]
@afischer211 I tried reproducing the bug, but are unable to. Could you give me some details on how you tried starting the exporter:

- Did you use the Docker image or just run the binary?
- Did you use command-line options or the environment?
- What URL (if possible the exact one) did you use which was rejected?

Thanks.

**Comment by afischer211** [comment]
Hello, sorry for the delayed answer.
* I use the docker image xperimental/nextcloud-exporter:latest
* I start it with command-line option "-l https://<address>:<port>/<path> (over a docker-compose-file)
* The error-message is: Error in configuration: info URL is not valid: parse  https://<address>:<port-number>/ocs/...: first path segment in URL cannot contain colon

I think, an url with port-number is also a valid url (not only default ports 80 and 443).

**Comment by xperimental** [comment]
Thanks for the information. Unfortunately I still can not reproduce the bug you mentioned.
I am using docker 19.03 and docker-compose 1.24. My docker-compose file looks like this:

```yml
version: "3"
services:
  exporter:
    image: xperimental/nextcloud-exporter
    command:
    - "-l"
    - "https://example.com:1234/ocs/v2.php/apps/serverinfo/api/v1/info"
    - "-u"
    - "someuser"
    - "-p"
    - "somepass"
```

I don't get an error message when using the above configuration (except that the server can not be reached when actually scraping the metrics). Can you perhaps post the docker-compose file you are using?
