### ISSUE TITLE
Token authentication invalid header

### ISSUE THREAD

**Issue by Jeroen0494** [xperimental/nextcloud-exporter#82]
Hi,

Token authentication doesn't seem to work currently. I receive the following errors:

```
level=info msg="nextcloud-exporter 0.6.0"
level=info msg="Nextcloud server: http://nextcloud Authentication using token."
level=info msg="Listen on :9205..."
level=error msg="Error during scrape: Get \"http://nextcloud/ocs/v2.php/apps/serverinfo/api/v1/info?format=json\": net/http: invalid header field value for \"Nc-Token\""
```

I use the following config:
```
---
# Source: nextcloud/templates/metrics-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/policy: "minor"
  name: nextcloud-metrics
  namespace: nextcloud
  labels:
    app: nextcloud-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-metrics
  template:
    metadata:
      labels:
        app: nextcloud-metrics
        fritz.box/egress-nextcloud: true
    spec:
      containers:
      - name: metrics-exporter
        image: "xperimental/nextcloud-exporter:0.6.0"
        imagePullPolicy: IfNotPresent

        env:
        - name: NEXTCLOUD_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: nextcloud-creds
              key: nextcloud-auth-token
        - name: NEXTCLOUD_SERVER
          value: http://nextcloud
        - name: NEXTCLOUD_TIMEOUT
          value: 5s

        ports:
        - name: metrics
          containerPort: 9205

        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            add:
              - NET_BIND_SERVICE
            drop:
              - ALL
          seccompProfile:
            type: Localhost
            localhostProfile: operator/nextcloud/nextcloud-metrics-exporter-seccomp-profile.json

        resources:
          requests:
            memory: 10Mi
            cpu: 10m
          limits:
            memory: 100Mi
```

The reason I tried the token, was because the username and password were working for login but not for retrieving metrics.

nextcloud-metrics logs
```
level=error msg="Error during scrape: unexpected status code: 400"
```

Nextcloud trusted domains
```
/var/www/html $ php ./occ config:system:get trusted_domains
localhost
nextcloud.mediaserver.fritz.box
app
nextcloud-metrics
```

Nextcloud logs
```
127.0.0.1 - admin 19/Jan/2023:16:12:14 +0000 "GET /ocs/v2.php" 400
```

Nextcloud version `24.0.8-fpm-alpine`
